on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ${{ matrix.service }}
    strategy:
      max-parallel: 1
      matrix:
        service:
          - a
          - b
          - c
          - d
          - e
          - f
          - g
          - h
          - i
          - j
          - k
          - l

    steps:
      - run: echo ${{ matrix.service }}
